### ISSUE TITLE
I could not run it successfully. I am giving full derails below. Please have a watch. Thanks.

### ISSUE THREAD

**Issue by najmul-csebuet** [pvzig/SlackKit-examples#2]
najmul.csebuet@Mds-Mac ~/D/g/S/E/Leaderboard> carthage update
**\* Fetching slackkit
**\* Fetching swifter
**\* Fetching Starscream
**\* Checking out Starscream at "2.0.0"
**\* Checking out swifter at "3.0.3"
**\* Checking out slackkit at "3.1.1"
**\* xcodebuild output can be found in /var/folders/ds/27v220vj3rz03dt6bywlrsmh0000gn/T/carthage-xcodebuild.FsAikn.log
**\* Building scheme "Starscream" in Starscream.xcodeproj
**\* Building scheme "StarscreamOSX" in Starscream.xcodeproj
**\* Building scheme "StarscreamTv" in Starscream.xcodeproj
**\* Building scheme "SwifteriOS" in Swifter.xcodeproj
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
A shell task (/usr/bin/xcrun xcodebuild -project "/Users/najmul.csebuet/Documents/github libs/SlackKit-examples/Examples/Leaderboard/Carthage/Checkouts/swifter/XCode/Swifter.xcodeproj" -scheme SwifteriOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

najmul.csebuet@Mds-Mac ~/D/g/S/E/Leaderboard>

**Comment by pvzig** [comment]
Sorry for the delayed response, I wasn't watching this repo.

```carthage update --configuration "Debug"``` completes successfully for me, might have been a bad `Swifter` tag when you tried it.
